Sergih28/groc

app/README.md

Added initial setup section to the app Readme

Add initialize project section to app readme

---

README.md

Updated README to include the license section

Add license section to README

---

.github/ISSUE_TEMPLATE/bug.yaml
.github/ISSUE_TEMPLATE/feature.yaml
.github/ISSUE_TEMPLATE/general.yaml
.github/ISSUE_TEMPLATE/translation.yaml

Replaced issue templates titles to an empty string
- Addresses #20 

Replaced issue templates titles to an empty string

---

README.md

Added code and repo size to the README
- Addresses #22 

Add badges for repo and code size

---

.github/workflows/playwright.yml
app/.gitignore
app/README.md
app/package.json
app/playwright.config.ts
app/tests/e2e/example.spec.ts

This pull request includes the installation of playwright with some temporary examples and a github workflow to run them automatically when creating a pull request.
- Addresses #13 

Install and config playwright

---

docs/decisions/0001-automatic-translations-decision.md

Added the folder structure for MADR files and the MADR decision for the automatic or manual translations in the project.
- Addresses #36 

Add manual translation decision MADR

---

docs/decisions/0003-package-version.md

Add the decision AMDR regarding package version
- Addresses #38 

Add package version decision MADR

---

docs/decisions/0004-global-state-library.md

Add global state library decision AMDR

---

CODE_OF_CONDUCT.md
README.md
app/README.md
docs/decisions/0001-automatic-translations.md
docs/decisions/0002-conventional-commits.md
docs/decisions/0003-package-version.md
docs/decisions/0004-global-state-library.md

Linted and fixed all the formatting issues of all markdown files
- Addresses #46 

Format and fix all MD documents

---

app/src/layouts/Layout.astro

Added favicon.
- Addresses #26 

Change favicon

---

translations/readme/README.cat.md
translations/readme/README.es.md
translations/readme/README.jp.md
translations/readme/README.kr.md

Added README translations for Catalan, Spanish, Korean and Japanese.
- Addresses #45 

Translate main README to other languages

---

.husky/pre-push
app/package.json

Added husky pre-push hook to run unit tests and added a unit test script on the package.json
- Addresses #50 

Add husky pre-push hook to run unit tests

---

docs/decisions/0005-date-library.md

Added MADR decision about what date library the project is going to use.
- Addresses #35 

Add date library MADR decision and installation

---

app/README.md
app/config/.tmuxinator.yml
app/package.json

Addded tmuxinator template and tmuxinator script

---

app/tsconfig.json

Added folder imports in tsconfig.json
- Addresses #57 

Added folder imports

---

app/package.json

Added sonner

---

app/package.json

Added formik

---

app/package.json

Added react query
- Addresses #78 

Added react query

---

app/README.md

Added an optional setup section for installing tmux and tmuxinator. Also fixed a typo in the Command section where a dot was missing.
- Addresses #63 

Added optional setup for tmux and tmuxinator and fixed typo

---

app/tsconfig.json

Added hooks and errors folder import to tsconfig.json

Add hook named import

---

app/bunfig.toml
app/happydom.ts
app/package.json

Add happydom and its config files needed for testing with the DOM

Add config for dom testing

---

app/package.json

Add react-testing-library, happydom and its config files needed for testing with the DOM

Add dependencies and config for dom testing

---

docs/decisions/0007-change-package-manager.md

Add MADR decision for changing package manager from bun to pnpm

Add package manager change MADR

---

docs/decisions/0008-testing-framework.md

Add MADR decision for the testing framework after changing package manager from bun to pnpm

Add test framework MADR decision

---

app/src/components/Button.tsx
app/src/stories/Button.stories.tsx
app/tests/unit/Button.test.tsx

Created the main button component and a story to test it.
- Addresses #70 

Create the main button component and its story

---

app/src/components/PlayPauseButton.tsx
app/src/stories/PlayPauseButton.stories.tsx
app/tests/unit/PlayPauseButton.test.tsx

This branch comes from a branch that is not yet merged (see #70).
Added PlayPause button component and its story to test.
- Addresses #68 

68 create play pause button component in storybook

---

app/src/components/ResetButton.tsx
app/src/stories/ResetButton.stories.tsx
app/tests/unit/ResetButton.test.tsx

This branch was created from another branch that is not yet merged (see #70)
Added a Reset button component and its story
- Addresses #72 

Add Reset button and story test

---

app/src/components/NextButton.tsx
app/src/stories/NextButton.stories.tsx
app/tests/unit/NextButton.test.tsx

Added a next button component and its story to test. This branch has changes not yet merged (see #70)
- Addresses #74 

74 create next button story

---

app/src/components/Switch.tsx
app/src/stories/Switch.stories.tsx
app/tests/unit/Switch.test.tsx

Added Switch component and its story to test
- Addresses #77 

Add Switch component and its story

---

app/src/components/Slider.tsx
app/src/stories/Slider.stories.tsx
app/tests/unit/Slider.test.tsx

Added slider component and its story to test
- Addresses #69 

Added Slider component and story

---

app/src/data/pomodoSampleData.json

Added JSON with mock data
- Addresses #71 

Add mock pomodoro data

---

app/pnpm-lock.yaml
app/src/stories/Button.stories.tsx
app/src/stories/NextButton.stories.tsx
app/src/stories/ResetButton.stories.tsx
docs/decisions/0005-date-library.md

Update pnpm lock file and fix eslint errors that appeared when pushing the branch.
- No issue

Update pnpm lock and fix eslint errors

---

app/package.json

Updated Astro from v3 to v4.
- Adressess #107 

Update astro to astro 4.0.4

---

app/src/components/Footer.tsx
app/src/hooks/useYearRange.tsx
app/src/stories/Footer.stories.tsx
app/tests/unit/Footer.test.tsx
app/tests/unit/yearRange.test.ts

Installed react-icons, a Footer component and its story
- Addresses #67 

67 create the footer component in storybook

---

app/src/components/Button.tsx
app/src/components/Settings.tsx
app/src/components/ui/input/InputNumber.tsx
app/src/components/ui/input/InputRadio.tsx
app/src/stories/Settings.stories.tsx
app/tests/unit/Settings.test.tsx
app/tests/unit/__snapshots__/Settings.test.tsx.snap

Created Settings component, InputRadio and InputNumber UI compoents, and created the test and stories for the compoent
- Addresses #79 

Create Settings component and tests

---

app/src/components/ProgressBar.tsx
app/src/errors/CurrentAboveBaseError.tsx
app/src/errors/CurrentAboveTargetError.tsx
app/src/errors/CurrentBelowBaseError.tsx
app/src/errors/CurrentBelowTargetError.tsx
app/src/stories/ProgressBar.stories.tsx
app/tests/unit/ProgressBar.test.tsx
app/tests/unit/calculatePercentage.test.tsx
app/tests/unit/helpers.tsx
app/vite.config.ts

Add ProgressBar component, its story in storybook and unit test
- Addresses #106 

106 add progress bar component

---

README.md
translations/readme/README.cat.md
translations/readme/README.es.md
translations/readme/README.jp.md
translations/readme/README.kr.md

Add translation section with redirects and flags for other languages

---

app/src/components/Counter.tsx
app/src/hooks/useCounter.tsx
app/src/stories/Counter.stories.tsx
app/tests/unit/Counter.test.tsx
app/tests/unit/calculateCounter.test.ts

Added a Counter component, useGetCounter hook and a story to test in Storybook
- Addresses #58 

Made Counter component, counter hook and story

---

app/package.json

Update Astro to 4.0.7. With this update, there are no errors when running the build command.
- Addresses #118 

Update Astro to 4.0.7

---

app/tests/unit/Footer.test.tsx

Fixed Footer tests due to improper year mocking in certain cases
- Addresses #125

Fix Footer unit test 

---

app/src/components/Notification/index.tsx
app/src/components/Notification/types.tsx
app/src/stories/Notification.stories.tsx
app/tests/unit/Notification.test.tsx

Add notification component and stories to test
- Addresses #80 

Create a nofitication component and stories in storybook

---

app/package.json
app/stylelint.config.js

Added stylelint and its config.
- Addresses #75 

Add Stylelint and stylelint config

---

.github/workflows/playwright.yml
app/compose.yaml
app/playwright.config.ts
app/tests/e2e/NavBar.spec.ts
app/tests/e2e/utils.ts

Fix the playwright github hook. Currently it does not complete even though the tests work.
- Fixes #151

Fix playwright github hook

---

.github/workflows/unit-test.yml

Set up a GitHub Action to automatically run unit tests on every push or pull request
- Addresses #137 

Add Github Action unit test

---

README.md
translations/readme/README.cat.md
translations/readme/README.es.md
translations/readme/README.jp.md
translations/readme/README.kr.md

Add Special Thanks section de README and its translations.
- Addresses #154 

Add Special Thanks section de README and its translations

---

app/Makefile

Add bash command to enter the _dev_ container shell.
- Addresses #158 

Add bash command to Makefile

---

.github/workflows/eslint.yml

Add eslint action

---

app/Makefile
app/src/components/layouts/layout/index.astro
app/src/features/pomodoro/services/local-storage/types.ts

Add command to run test-coverage in Makefile

Add test-coverage command

---

app/src/components/layouts/footer/styles.css
app/src/components/layouts/layout/index.astro
app/src/components/layouts/main/index.astro
app/src/components/layouts/navbar/styles.css
app/src/features/pomodoro/components/phase-selector/index.tsx
app/src/features/pomodoro/styles.css

Enhanced readability and visibility by addressing style inconsistencies across elements and text.
- Addresses #173

Fix color inconsistency in light and dark mode

---

app/package.json
app/pnpm-lock.yaml
app/src/features/pomodoro/components/counter/components.tsx
app/src/features/pomodoro/components/counter/counter.test.tsx
app/src/features/pomodoro/hooks/use-get-animated-counter-content.tsx
app/src/features/pomodoro/styles.css
app/src/stores/pomodoro/actions.ts
app/src/stores/pomodoro/constants.ts
app/src/styles/index.css

Added animated counter numbers with react spring.
Fixed counter tests after the counter animations were added.
- Addresses #160 

Add react spring

---

app/Makefile

Added `make install` command that executes `pnpm install --lock-file'` in the dev container.
- Addresses[ #53](https://tree.taiga.io/project/sergih28-groc/task/53)

Add 'make install' command in Make

---

docs/database.md

Added the E-R diagram of the database made with mermaid.
- Addresses [ #456](https://tree.taiga.io/project/sergih28-groc/task/14)

Add database E-R diagram

---

app/Makefile
app/compose.yaml

Enhance Makefile with command descriptions and self-documentation
Added descriptive comments next to each command to document their purpose. Updated the 'help' command to utilize self-documentation, providing a clearer overview of available targets and their descriptions.
Made the 'help' command the default target.

Update Makefile for self-documentation

---

.husky/pre-push
app/Makefile

Mofified the pre-push husky script to run the unit tests in docker instead of running them in local.
- Addresses [#22](https://tree.taiga.io/project/sergih28-groc/task/22)

Run pre-push tests in docker container

---

.github/pull_request_template.md

Updated the PR template, adding a new section about the changelog.
- Addresses #189 

Updated PR template adding a Changelog section
